In [1]:
from PIL import Image, ImageDraw
import numpy as np
from heat_experiment_2d import HeatExperiment2D
from random_shape import generate_smooth_blobs, generate_line
%matplotlib widget

In [2]:
width, height = 128, 128
image = generate_smooth_blobs(width, height)
image.save("random_shape.png")
image = generate_line(width, height)
image.save("random_line.png")

In [3]:
# image = Image.new("1", (width, height), color=1)
# draw = ImageDraw.Draw(image)

# x = rnd.randint(30, width - 30)
# y = rnd.randint(30, height - 30)
# num_turns = rnd.randint(0, 3)
# angle = rnd.random() * 2 * np.pi
# thickness = rnd.randint(6, 12)
# pts = np.linspace(-width)
# if num_turns == 0:
#     pts = [
#         (x - np.cos(angle) * width, y - np.sin(angle) * height),
#         (x + np.cos(angle) * width, y + np.sin(angle) * height),
#     ]
# else:
#     pts = []
#     sign = 1
#     for i in range(-num_turns, num_turns+1):
#         angle = rnd.uniform()
#         step_size = rnd.randint(5, 11)
#         pt_x = x + i*sign * step_size * np.sin(angle)
#         pt_y = y - i*sign * step_size * np.cos(angle)
#         pts.append([np.round(pt_x), np.round(pt_y)])
#         sign *= -1
# # draw.line([], fill=0, width=thickness)
# pts = np.array(pts)
# print(pts)
# print(pts[:,0], pts[:,1])
# draw.line([pts[:, 0], pts[:, 1]], fill=0, width=thickness)
# image.save("random_line.png")

In [4]:
# image = Image.new("1", (width, height), color=1)
# draw = ImageDraw.Draw(image)

# angle = np.pi / 2  # 0.5*np.pi*rnd.uniform(-1, 1)
# x = np.arange(-width, 2 * width, step=1, dtype=np.float64)
# # x = np.arange(0, width, step=1)
# # y = np.ones(3*height)*height//2
# y = np.zeros(len(x))
# y = x * np.sin(angle) #+ height // 2
# #x += x * np.cos(angle) #+ width // 2
# # y += height // 2
# pts = [(x[i], y[i]) for i, _ in enumerate(x)]
# thickness = rnd.randint(6, 12)
# # draw.line(np.column_stack([x,y]), fill=0, width=thickness)
# draw.line(pts, fill=0, width=thickness)
# image.save("random_line.png")

In [5]:
# from scipy.interpolate import CubicSpline
# from numpy.random import default_rng
# rng = default_rng()
# point_count = rng.integers(3, 6)
# rand_x = rng.choice(width, size=point_count, replace=False)
# rand_y = rng.integers(0, height+1, point_count)
# pts = [(x, y) for x,y in zip(rand_x, rand_y)]
# pts.sort(key=lambda x: x[0])
# pts = np.array(pts)
# spline = CubicSpline(pts[:,0], pts[:,1])
# x = np.linspace(0, width, width)
# y = spline(x)
# pts = [(x[i], y[i]) for i, _ in enumerate(x)]
# image = Image.new("1", (width, height), color=1)
# draw = ImageDraw.Draw(image)
# thickness = rnd.randint(6, 12)
# draw.line(pts, fill=0, width=thickness)
# image.save("random_line.png")

In [6]:
# from scipy import interpolate as interp
# from numpy.random import default_rng
# rng = default_rng()
# point_count = 6#rng.integers(12,14)
# thickness = rng.integers(6, 12)
# rand_x = rng.choice(width, size=point_count, replace=False)
# rand_x.sort()
# rand_y = rng.choice((0, height+1), size=point_count)
# pts = [(x, y) for x,y in zip(rand_x, rand_y)]
# pts = np.array(pts)
# tck,u = interp.splprep(pts.transpose(), s=0)
# unew = np.arange(0, 1.01, 0.01)
# out = interp.splev(unew, tck)
# pts = [(x, y) for x,y in zip(out[0], out[1])]
# image = Image.new("1", (width, height), color=1)
# draw = ImageDraw.Draw(image)
# # draw.line(pts, fill=0, width=thickness)
# draw.point(pts)
# image.save("random_line.png")

In [7]:
from numpy.random import default_rng
rng = default_rng()
thickness = 10
A = np.array([width//2, height//2])
angle = rng.random()*2*np.pi
B = A + np.array([np.cos(angle), np.sin(angle)])*2*width
C = A - np.array([np.cos(angle), np.sin(angle)])*2*height
shift = np.array([rng.integers(-width//2, width//2), rng.integers(-height//2, height//2)])
B += shift
C += shift
pts = [tuple(C), tuple(B)]
image = Image.new("1", (width, height), color=1)
draw = ImageDraw.Draw(image)
draw.line(pts, fill=0, width=thickness)
image.save("random_line.png")
C, A, B

(array([  74.425711  , -231.83402492]),
 array([64, 64]),
 array([-68.425711  , 259.83402492]))